=== m1m0sin/xml-and-json-course/02-xml/ejemplo/catalogo-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element 
                    name="producto" 
                    minOccurs="1" 
                    maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element 
                                name="nombre" 
                                type="xs:string" />
                            <xs:element 
                                name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element 
                                name="stock" 
                                type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="P\d{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute 
                            name="categoria" 
                            type="xs:string" 
                            use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== m1m0sin/xml-and-json-course/02-xml/ejemplo/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="catalogo-schema.xsd">
    <producto id="P001">
        <nombre>Product 001</nombre>
        <precio>100.00</precio>
        <stock>10</stock>
    </producto>
    <producto id="P002" categoria="ELEC">
        <nombre>Product 002</nombre>
        <precio>120.00</precio>
        <stock>0</stock>
    </producto>
    <producto id="P003">
        <nombre>Product 003</nombre>
        <precio>85.50</precio>
        <stock>3</stock>
    </producto>
</catalogo>
